Added the BenchmarkRunner class  and SYCL dp benchmarks
oneapi-src/distributed-ranges pull request #294
Opened 2023-05-29 09:38 UTC by haichangsi

Added a new python class to run benchmarks faster and easier.

Added 2 new dot product benchmarks based on SYCL only - using USM and buffers.

Introduced CsvPlotter to autogenerate plots.

2023-05-29 10:16 UTC, rscohn2 commented
I added google benchmark. There is dot product, fill, copy, stencil, ... It is a common infrastructure for running/reporting multiple benchmarks. It supports shp/mhp as well as using DPL/SYCL with DR.

Can you add whatever you need there instead?

2023-05-29 11:42 UTC, mateuszpn commented on examples/shp/dot_product_benchmark.cpp
> +  // fmt::print("devices, size, shp_time, dpl_time\n");
The code that is no longer used should be removed, especially if it is trivial (like printing messages).

2023-05-29 11:42 UTC, mateuszpn commented on examples/shp/dot_product_benchmark.cpp
> +  std::size_t ndev = 0; // size of problem
"// number of devices" probably. Comments are good if they are precise

2023-05-29 12:38 UTC, mateuszpn requested changes
In general, I'd give a gbench (mentioned by Robert) a look, and probably make benchmarks uniform. The system is similar to gtest. The extra work will bring time savings in the future (we will do a lot of benchmarks).

2023-05-29 12:38 UTC, mateuszpn commented on examples/shp/dot_product_sycl.cpp
> +    std::size_t chunk_size = vec_size / dev_num;
You get better (more uniform) distribution when last node is less loaded than the others:
chunk_size = vec_size / (dev_num - 1);
last_chunk_size = vec_size - chunk_size * (dev_num - 1);

2023-05-29 12:38 UTC, mateuszpn commented on examples/shp/dot_product_sycl_buffers.cpp
> +  if (vec_size == 0 || dev_num == 0) {
Consider a message here, do not finish with no word.

2023-07-19 19:16 UTC, rscohn2 commented
> It should be closed probably unless we want to use a part of it (pure SYCL dot product code @lslusarczyk ) @rscohn2

Closing, we can refer to the PR if we need the code.

2023-07-19 19:16 UTC, closed without merging