add ut for shp:fill and new DV constructors
oneapi-src/distributed-ranges pull request #69
Opened 2023-03-02 09:41 UTC by haichangsi

2023-03-02 13:05 UTC, rscohn2 approved these changes

2023-03-09 10:47 UTC, lslusarczyk requested changes

2023-03-09 10:47 UTC, lslusarczyk commented on test/gtest/shp/containers.cpp
> +// TODO: add more tests: fill_constructor_one_item, fill_constructor_no_items
@haichangsi , as an exercise of writing concise UTs please implement this TODO and TODO below

2023-03-10 08:25 UTC, lslusarczyk requested changes

2023-03-10 08:25 UTC, lslusarczyk commented on test/gtest/shp/containers.cpp
> +  EXPECT_TRUE(equal(typename TestFixture::DistVec(1),
this ctor initializes with random value, both vectors may be different
use ctor with explicit value, e.g DistVec(1,77), LocalVec(1, 77)

2023-03-10 08:45 UTC, lslusarczyk approved these changes

2023-03-10 09:41 UTC, merged

2023-03-10 11:47 UTC, rscohn2 commented
@lslusarczyk Can these be made into shared tests (mhp/shp)? mhp does not support initializer list in the constructor. That would be a good thing to add.

2023-03-10 15:06 UTC, lslusarczyk commented
sure, created https://github.com/oneapi-src/distributed-ranges/issues/104 for this