mhp::sort() performance optimization with dpl::lower_bound
oneapi-src/distributed-ranges pull request #742
Opened 2024-04-23 13:46 UTC by mateuszpn

Joint work with @haichangsi

2024-06-06 14:51 UTC, lslusarczyk requested changes

2024-06-07 14:39 UTC, mateuszpn commented on include/dr/mhp/algorithms/sort.hpp
> +    for (std::size_t _i = 1; _i < vec_split_i.size(); _i++) {
This code is common for sycl and non-sycl block, so moving it to the common block of code makes sense. Still, it belongs logically to splitters calculations (in fact vec_split_s contains key results of the splitters function) so I do not think moving it outside the function is reasonable.

2024-06-07 14:42 UTC, mateuszpn commented on include/dr/mhp/algorithms/sort.hpp
>  #ifdef SYCL_LANGUAGE_VERSION
In fact the buffer class is universal and not bind to sorting in any way, so the class is moved to global.hpp. copy() function hiding ifdefs is put in global.hpp, too.

2024-06-24 06:18 UTC, lslusarczyk approved these changes
self applied last of my comments, reorganized a bit header files

2024-06-24 09:26 UTC, merged